### ISSUE TITLE
Typescript issue with node 16

### ISSUE THREAD

**Issue by ravijethvaaphp** [nbesli/pdf-merger-js#141] opened 2024-05-01 10:59 UTC
I have two issues with node16 and type script, i have fixed it locally but it's not allowing to create PR and pushing branch in repo, 
i am sending the screenshot of the change i have done it, if it's fine , 
<img width="890" alt="Screenshot 2024-05-01 at 4 29 11 PM" src="https://github.com/nbesli/pdf-merger-js/assets/4012270/36ee6bdd-0b32-4044-a7bf-9b5e49f338b8">
<img width="943" alt="Screenshot 2024-05-01 at 4 29 18 PM" src="https://github.com/nbesli/pdf-merger-js/assets/4012270/70f71120-2151-4bd6-8875-49e704e93d44">
can you please allow me to push in repo ?

**Comment by mojoaxel** [comment] 2024-06-17 21:36
[A fix](/nbesli/pdf-merger-js/pull/137) by @dhunganabibek has been released as [v5.1.2](/nbesli/pdf-merger-js/releases/tag/v5.1.2) :rocket:

**Comment by mojoaxel** [comment] 2024-06-17 21:37
duplicate of #136

**Closed by mojoaxel** 2024-06-17 21:36 UTC
