### ISSUE TITLE
Invalid type definition in index.d.ts - Typescript 5.4.3

### ISSUE THREAD

**Issue by d4rkstar** [nbesli/pdf-merger-js#139] opened 2024-03-27 11:52 UTC
Hello,
using version 5.1.1 with typescript 5.4.3 i get this error:

```node_modules/pdf-merger-js/index.d.ts:49:3 - error TS2666: Exports and export assignments are not permitted in module augmentations.```

It seems that something is wrong in file index.d.ts:

**Comment by mojoaxel** [comment] 2024-06-17 21:36
[A fix](/nbesli/pdf-merger-js/pull/137) by @dhunganabibek has been released as [v5.1.2](/nbesli/pdf-merger-js/releases/tag/v5.1.2) :rocket: 
Please let me know if this is still an issue.

**Comment by mojoaxel** [comment] 2024-06-17 21:56
closing as duplicate of #136

**Closed by mojoaxel** 2024-06-17 21:56 UTC
Labels: bug, duplicate
