### ISSUE TITLE
Is the wrong version uploaded at npm?

### ISSUE THREAD

**Issue by rnenjoy** [nbesli/pdf-merger-js#132] opened 2024-01-15 15:26 UTC
I installed version 5 from npm but getting error on getInputAsBuffer-function. Which doesnt exist in the code in github at all.

Is the wrong version on npm or something?

**Comment by rnenjoy** [comment] 2024-01-15 15:40
I'm sorry. I mean yarn, i install with yarn.

**Comment by mojoaxel** [comment] 2024-01-27 10:45
@rnenjoy Could you please provide more details on that error and maybe even pdf files to reproduce this error. Thx!

**Comment by mojoaxel** [comment] 2024-06-17 21:29
@rnenjoy Is this still an issue with the newest version?

**Comment by mojoaxel** [comment] 2024-06-24 07:53
I'm closing this because it missing necessary context.

@rnenjoy Feel free to let us know if this is still an issue for you!

**Closed by mojoaxel** 2024-06-24 07:53 UTC
Labels: bug
